vich_uploader:
    db_driver: orm

    mappings:
        picture_file:
            uri_prefix: '%app.path.picture_file%'
            upload_destination: '%kernel.project_dir%/public%app.path.picture_file%'
            delete_on_update: true
            delete_on_remove: true
            inject_on_load: false
            namer:
                service: Vich\UploaderBundle\Naming\UniqidNamer

        profile_picture_file:
            uri_prefix: '%app.path.profile_picture_file%'
            upload_destination: '%kernel.project_dir%/public%app.path.profile_picture_file%'
            delete_on_update: true
            delete_on_remove: true
            inject_on_load: false
            namer:
                service: Vich\UploaderBundle\Naming\UniqidNamer
        
        banner_file:
           uri_prefix: '%app.path.banner_file%'
           upload_destination: '%kernel.project_dir%/public%app.path.banner_file%'
           delete_on_update: true
           delete_on_remove: true
           inject_on_load: false
           namer:
                service: Vich\UploaderBundle\Naming\UniqidNamer
        
